### ISSUE TITLE
how to get color from colorPalettePreference

### ISSUE THREAD

**Issue by e4basil** [michael-rapp/AndroidMaterialPreferences#10]
I am new Android preference activity
how to get color from colorPalettePreference

**Comment by michael-rapp** [comment]
Preferences in general store key-value pairs as so called "shared preferences" (see here for further information: http://developer.android.com/training/basics/data-storage/shared-preferences.html). The `ColorPalettePreference` stores a color as an `Integer` value. The key, which is used for storing the color is the key you have specified using the preference's `setKey`-method or the `android:key` attribute, when defining the preference in a XML resource. You can retrieve the color using the following code:

```java
SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context);
int color = sharedPreferences.getInt("key", defaultValue);
```

The default value is used if the user has not selected a color using the preference yet. It should be the same color as you have specified using the `android:defaultValue` XML attribute.

Alternatively, if you want to observe when the preference's color has been changed, you can register an `OnPreferenceChangeListener` by using the preference's `setOnPreferenceChangeListener`-method. The listener's `onPreferenceChange`-method is then called whenever the user selects a color, passing the new color as a method parameter. However, you eventually have to cast the value to an `Integer`.

**Comment by e4basil** [comment]
thanks i got it
