### ISSUE TITLE
How to fetch preference details on app first startup

### ISSUE THREAD

**Issue by e4basil** [michael-rapp/AndroidMaterialPreferences#11]

**Comment by michael-rapp** [comment]
I guess you want to read the preference's default value on startup, right?

What I normally do is to specify the key and default value as a resource. For example, if its value is a String, add them to your `res/values/strings.xml` like follows:

```xml
<string name="key">key<\string>
<string name="default_value">default value<\string>
```

Then use this resources to specify the preference's key and default value when defining it via XML:

```xml
android:key="@string/key"
android:default value="@string/default_value"
```

When loading the preference's current value in your Java code, load the String resources beforehead:

```java
String key = context.getString(R.string.key);
String defaultValue = context.getString(R.string.default_value);
SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context);
String currentValue = sharedPreferences.getString(key, defaultValue);
```

If the app's preference screen has not been shown yet and the preference has therefore not been initialized, the default value you have loaded from the `strings.xml` will be returned.
