### ISSUE TITLE
BadParcelableException

### ISSUE THREAD

**Issue by bagintz** [michael-rapp/AndroidMaterialPreferences#13]
I am getting a lot of these errors when using this library, any ideas?:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{[APP]MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: de.mrapp.android.preference.AbstractDialogPreference$SavedState

**Comment by michael-rapp** [comment]
This was already happening some time ago, but I wasn't able to fix it back then (see https://github.com/michael-rapp/AndroidMaterialPreferences/issues/2). I will take a look at it again.

**Comment by michael-rapp** [comment]
I attempted to fix this in the recently released version 2.4.2. I am not one-hundred percent sure it did the trick though, as it is really hard to reliably reproduce this issue. Please feel free to re-open this bug report, if it occurs again.

**Comment by bagintz** [comment]
Ok, I got a significant amount from my last app release, so I will let you know if this comes back!

**Comment by michael-rapp** [comment]
Just out of curiosity, what's the name of your app?

**Comment by bagintz** [comment]
Signal Spy
