### ISSUE TITLE
Setting List looks different on Jelly Beans, Lollipop, and Nougat

### ISSUE THREAD

**Issue by Senth** [michael-rapp/AndroidMaterialPreferences#15]
Hi again,

**Comments**
_I'm doing a quite extensive search for all variations in my app between versions and to smooth them out. That's why I find so many differences now :)_

_It feels like I've only found faults, but I really like your library and as I mentioned I went through many before I found this :) I think these are the last differences I've found from your libraries._

**Issue Description**
I found that the list style is different on different Android versions. The attached picture describes all of them, I also included an image from https://material.google.com/components/lists.html#lists-specs. 

- List item height on single line items
- Font size and opacity on Jelly Beans
- Left/right padding on Jelly Beans and Lollipop
- Divider length on Jelly Beans and Lollipop (if there should be any divider).

![different_styles](https://cloud.githubusercontent.com/assets/2499370/18477866/76df3b10-79cf-11e6-98d2-6eaea3461a1b.png)

**Comment by michael-rapp** [comment]
The following aspects are in the responsibility of the library and I will attempt to fix them: 
- Font size and opacity
- List item height

The remainig aspects are not part of this library and there is no possibility to affect them from within it. They depend on how the preferences are composed/layouted by the parent container (usually they are placed within a `PreferenceCategory`, which itself is part of a `PreferenceFragment` or `PreferenceActivity`).
- Left/right padding
- Divider length

If you're using the Android SDK's `PreferenceFragment` and/or `PreferenceActivity` it is responsible for the preferences being displayed differently across different OS versions. I've written an alternative implementation of these classes, where the dividers should be stretched to the whole available width (see https://github.com/michael-rapp/AndroidPreferenceActivity).

The Material Design guidelines aren't very specific about when to show/hide the dividers between list items. For example, here is a screenshot with the dividers being visible: https://material-design.storage.googleapis.com/publish/material_v_9/0Bx4BSt6jniD7clprVXFrZGZ6QWM/patterns_settings_sliders.png

**Comment by michael-rapp** [comment]
I have realized, that the preferences of the library extend from the Android SDK's class `android.preference.Preference` and do not override any style attributes. This can easily be done by creating a custom layout for the preferences as described [here](http://stackoverflow.com/questions/6194116/creating-a-custom-layout-for-preferences). However, I will not do so, because if someone is using the library's preferences together with other preferences, this will cause them to look different from each other.
