### ISSUE TITLE
Migrate to use the Preference Support Library

### ISSUE THREAD

**Issue by bagintz** [michael-rapp/AndroidMaterialPreferences#17]
It seems that the plain ole "Preference" is going to be deprecated in Android P.  Is this going to work with the Support Library version?

Thanks!

**Comment by michael-rapp** [comment]
Do you have any information about this? I could not find anything.

At the moment, the library's preferences extend the class `android.preference.Preference` and therefore do not use the support library. It would be necessary to extend the support library's `Preference` class instead. As the support library mimics the behavior of the original SDK classes, no big changes should be necessary.

**Comment by bagintz** [comment]
@michael-rapp 
Any pages that reference older non support classes (e.g. Fragment, FragmentTransaction, etc etc) show the small dialog box.  See here for example: https://developer.android.com/reference/android/app/FragmentManager.html

![screenshot 2018-04-03 17 28 00](https://user-images.githubusercontent.com/5341290/38276853-62c7d8fe-3764-11e8-889a-3667358b6e9b.png)

**Comment by michael-rapp** [comment]
I see... Thank you for pointing this out!

I guess it's time to move to the support library in future releases then.

**Comment by bagintz** [comment]
awesome, thanks!

**Comment by michael-rapp** [comment]
Let's keep this issue open as a reminder ;-)

**Comment by bagintz** [comment]
gotcha, I just love to check boxes!

**Comment by bagintz** [comment]
@michael-rapp I am working on this (not sure if it will fit for a PR, but will try).  I got it working with the support libraries, but the theme is not carrying over.  Where/How is the theme for the NumberPickerPreference set in my project (the one that uses your library) ?

**Comment by bagintz** [comment]
:-/ nevermind, found it.........

`custom:dialogThemeResource="@style/theThemeYouWant"`

**Comment by michael-rapp** [comment]
Great to hear that you are making progress! I am willing to accept a PR, or at least use your code as a starting point, if you succeed.

**Comment by bagintz** [comment]
![at-dawn-we-code](https://user-images.githubusercontent.com/5341290/38431918-d2441284-3993-11e8-92b1-072d3fefd540.jpg)

**Comment by bagintz** [comment]
@michael-rapp what do I run in the library to create a complete aar to include in my project for local tests?  I am getting an aar, but it seems to not include some dependencies.

**Comment by bagintz** [comment]
nevermind, found a good explanation here:

https://stackoverflow.com/questions/36916991/transitive-dependencies-for-local-aar-library

**Comment by bagintz** [comment]
https://github.com/michael-rapp/AndroidMaterialPreferences

**Comment by michael-rapp** [comment]
Sorry, I was very busy during the past weeks. I plan to release this in the next few days. Feel free to remind me, if nothing happens ;-)

**Comment by michael-rapp** [comment]
Version 4.0.0 of this library has just been released. Starting from this version the library will use the v14 Preference support library.

@bagintz Thank you very much for making essential contributions to this release!
