### ISSUE TITLE
NullPointerException in ListPreference

### ISSUE THREAD

**Issue by KeloCube** [michael-rapp/AndroidMaterialPreferences#21]
Hi, great library!

I ran into a NPE when updating the values array in a list preference. This happened during development, but could potentially happen in production as well if an update modified the values array. I think it would be better if the library silently falled back to a default value or no value at all in this case.

`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
        at de.mrapp.android.preference.AbstractListPreference.indexOf(AbstractListPreference.java:202)`

https://github.com/michael-rapp/AndroidMaterialPreferences/blob/764b0177512d27d11406847bb44662036e0844b7/library/src/main/java/de/mrapp/android/preference/AbstractListPreference.java#L202

**Comment by KeloCube** [comment]
Oops, my bad. This was not due to having modified the values but I accidentally changed to an <array> from the <string-array> xml element.

**Comment by michael-rapp** [comment]
Nevertheless, I made some changes to eliminate the chance of any NPE being thrown in that method. The changes are available in the new release 5.1.7.
