### ISSUE TITLE
Hide separators between ListPreference's rows

### ISSUE THREAD

**Issue by Rainer-Lang** [michael-rapp/AndroidMaterialPreferences#6]
There a separators between the list elements (rows). Is it possible to hide them?
Like here: http://www.google.com/design/spec/components/dialogs.html#dialogs-behavior ---> "Scrollable content exception"

**Comment by michael-rapp** [comment]
I think there is no easy way to do this. But according to the design guide, I think this should become the default anyway. I will change this in a future release soon.

**Comment by michael-rapp** [comment]
The separators are now hidden by default in version 2.0.2.
