### ISSUE TITLE
Grouping of preferences and icon in front

### ISSUE THREAD

**Issue by Rainer-Lang** [michael-rapp/AndroidMaterialPreferences#8]
like in the guidelines: http://www.google.com/design/spec/patterns/settings.html#settings-grouping-settings

**Comment by michael-rapp** [comment]
There are two ways for adding an icon to a preference:

1. In the `onCreate`-method `PreferenceFragment`, which contains the preference, use the `findPreference`-method to reference it using its id. Then call one of its `setIcon`-methods.

2. When defining the preference in a XML resource, use the `android:icon` attribute to specify a drawable resource.

However, this will not add an indent to the separators as they are not drawn by the library, but by the class `PreferenceFragment` of the Android SDK. 

The SDK is also responsible for grouping preferences. You can either programmatically add a `PreferenceCategory` to your `PreferenceFragment` or define it in your XML resource. Refer to http://developer.android.com/guide/topics/ui/settings.html#Groups for more information.
