### ISSUE TITLE
How can i open sub screen 

### ISSUE THREAD

**Issue by xufeifandj** [michael-rapp/AndroidMaterialPreferences#9]
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:custom="http://schemas.android.com/apk/res-auto">
        <de.mrapp.android.preference.SwitchPreference
            android:defaultValue="@bool/preference_default_home"
            android:key="@string/preference_key_default_home"
            android:summary="@string/set_as_default_summary"
            android:title="@string/set_as_default"
            />

    <PreferenceCategory android:title="@string/general_text">
        <de.mrapp.android.preference.SwitchPreference
            android:defaultValue="@bool/preference_default_leftscreen"
            android:key="@string/preference_key_launcher_leftscreen"
            android:summary="@string/preferences_title_leftscreen_summary"
            android:title="@string/preferences_title_leftscreen"
            android:icon="@drawable/setting_appearance_ic"/>

        <de.mrapp.android.preference.ListPreference
            android:defaultValue="@string/preference_default_effect"
            android:entries="@array/transition_effect_entries"
            android:entryValues="@array/transition_effect_entries_values"
            android:key="@string/preference_key_launcher_effect"
            android:summary="@string/preferences_title_effect_summary"
            android:title="@string/appearance_text"
            android:icon="@drawable/setting_appearance_ic"/>

        <PreferenceScreen android:title="@string/gesture_text"
            android:dependency="">
            <de.mrapp.android.preference.ListPreference
                android:defaultValue="@string/preference_default_effect"
                android:entries="@array/transition_effect_entries"
                android:entryValues="@array/transition_effect_entries_values"
                android:key="@string/preference_key_launcher_effect"
                android:summary="@string/preferences_title_effect_summary"
                android:title="@string/appearance_text"
                android:icon="@drawable/setting_appearance_ic"/>
        </PreferenceScreen>

    </PreferenceCategory>
</PreferenceScreen>

**Comment by michael-rapp** [comment]
Subscreens aren't in the scope of this library. It does only provide preferences, but no components for composing them. If you want to create subscreens, you have to create a XML file for each subscreen. Each of them specifying the preferences of one screen. Create classes extended from the Android SDK's class `PreferenceFragment` for displaying them. Additionally, you have to create another XML file, which specifies so called "preference headers". They mainly consist of a title and the full qualified class name of one of the fragments you have previously created. So each preference header represents a navigation item. Finally, you have to show the preference headers in a `PreferenceActivity`. Refer to http://developer.android.com/guide/topics/ui/settings.html#PreferenceHeaders for a more detailed explaination.

I have also written another library, which provides an alternative implementation of the Android SDK's `PreferenceActivity`. It backports Android 5's Material appearance to previous API levels. If this is interesting for you, you can find it here: https://github.com/michael-rapp/AndroidPreferenceActivity

**Comment by xufeifandj** [comment]
thank u
